### ISSUE TITLE
Game crashes when script loads

### ISSUE THREAD

**Issue by Neobugu** [FurkanS1821/AutoBuddy#1]
Since today morning, script crashes when loading, i thought it was a slow charge day, but almost 20 min passed and the client got stucked, (No response), and also got leaverbuster warning ha!

I guess something got wrong while loading, already tried erasing my appdata and tried to get an update with no luck

**Comment by FurkanS1821** [comment]
I have a very little amount of internet left, can you enable console from EB settings and then go into game, then tell me what is wrong?

**Comment by FurkanS1821** [comment]
Fixed.
